### ISSUE TITLE
Tried connecting to localhost but fails to connect

### ISSUE THREAD

**Issue by LiamKenneth** [sigilbaram/CloudMud#1]
Hi, I've been playing around with Node building a Mud and I'm looking at making a web client for it. But not sure how to get tcp sockets and web sockets to work together. 

I downloaded your client, worked fine connecting to Discworld but when I changed the address and port to look at my mud running on localhost. It never connects. Do you have any idea why?

Thanks

**Comment by sigilbaram** [comment]
Discworld is the mud I've been testing against and they have a websocket port set up on their server, so I haven't done anything as far as non websocket connections in the client yet, but I did run into this problem when I first tried to use websockets (I tried to connect to the normal port, 4242, on Discworld rather than the websocket specific port, 4243, before I realized there was a difference).

Currently JavaScript alone cannot connect to TCP ports directly. Instead, websockets use a separate protocol on top of TCP which puts data through HTTP like requests and a regular TCP server port will view the extra HTTP-like stuff as jibberish. Because of this, JavaScript requires  websocket support on the server, either directly in the server program or via a server side proxy/bridge or a proxy/bridge on the client using something like Java of Flash which handles the actual connection to the server.

As for why it's like this? A lot of people seem baffled by that same question... There isn't really a reason why JavaScript couldn't support pure TCP without the extra HTTP-like stuff, at least not that I  found and I found a lot of people asking for it.

If you're writing your mud server in Node then you should be able to make a second listening port for accepting websock connections or something along those lines. I haven't actually looked into it, but I would imagine websocket support is built into node, and it'd just be a matter of making sure your server has a listening port open for them and then the connection objects spawns by the two listening ports should look the same, in theory anyway. It's been a while since I wrote a server and that was in Java not node. heh

**Comment by LiamKenneth** [comment]
Thanks for the reply, I didn't know Discworld had a websocket port. I assumed your client done all the magic :-) What you said about adding a websocket server to my existing project worked! 

Thanks for helping me, I was pretty shocked by how easy it was. I was going down the wrong route completely before seeing your reply.
